[build]
# 并行编译
jobs = 4

[target.x86_64-unknown-linux-gnu]
# Linux目标配置
linker = "clang"

[alias]
# 常用别名
test-all = "test --all"
check-all = "check --all"
build-all = "build --all"
doc-all = "doc --all"

# 开发工具别名
fmt-check = "fmt -- --check"
clippy-fix = "clippy --fix" 