//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

mod database;
pub use database::{Config as DatabaseConfig, db_connect};

mod user;
pub use user::{
    ActiveModel as UserActiveModel, Column as UserColumn, Entity as UserEntity, Model as UserModel,
};

mod menu;
pub use menu::{
    ActiveModel as MenuActiveModel, Column as MenuColumn, Entity as MenuEntity, Model as MenuModel,
};

mod role;
pub use role::{
    ActiveModel as RoleActiveModel, Column as RoleColumn, Entity as RoleEntity, Model as RoleModel,
};

mod role_menu;
pub use role_menu::{
    ActiveModel as RoleMenuActiveModel, Column as RoleMenuColumn, Entity as RoleMenuEntity,
    Model as RoleMenuModel,
};

mod user_role;
pub use user_role::{
    ActiveModel as UserRoleActiveModel, Column as UserRoleColumn, Entity as UserRoleEntity,
    Model as UserRoleModel,
};

mod online;
pub use online::{
    ActiveModel as OnlineActiveModel, Column as OnlineColumn, Entity as OnlineEntity,
    Model as OnlineModel,
};
